### ISSUE TITLE
About this site link in the footer points to www.mozilla.org

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/birdbox#162]
The [About this site](https://www.mozilla.org/about/this-site/) link in the footer points to www.mozilla.org, which is a different project / tech stack to Birdbox. 

Should this link be omitted, or could birdbox have it's own page?

**Comment by stevejalim** [comment]
Ooh, good question. The current future.mozilla.org site's footer links to the same page too - probably because the original was a lift and shift from mozorg itself. 

We can drop the link for now I think. Once birdbox is a bit more mature and has its own demo site, that'd be a sensible place to link to
